API_KEY: API_KEY
units: metric
coordinates:
  lat: LAT
  lon: LON
refresh_period_min:
  data: 30
  screen: 1
city: CITY_NAME
metrics:
  record_metrics: false
  database_url: localhost:8086
  database_name: pi_db